spring.application.name=gateway-service
server.port=8085
routing.primary-server-url=http://localhost:8080
routing.replica1-server-url=http://localhost:8081
routing.replica2-server-url=http://localhost:8083
routing.reconcile-delay-ms=3000
