spring.application.name=server-replica2
server.port=8083
node.id=replica2
node.role=REPLICA
node.self-url=http://localhost:8083
cluster.node-urls=http://localhost:8080,http://localhost:8081,http://localhost:8083
