spring:
  application:
    name: server-primary

server:
  port: 8080

node:
  id: primary
  role: LEADER
  self-url: http://localhost:8080

cluster:
  node-urls: http://localhost:8080,http://localhost:8081,http://localhost:8083
