spring.application.name=server-replica
server.port=8081
node.id=replica1
node.role=REPLICA
node.self-url=http://localhost:8081
cluster.node-urls=http://localhost:8080,http://localhost:8081,http://localhost:8083
